version: "3.6"

services:
    mariadb:
        container_name: mariadb
        image: mariadb:10.6.10
        env_file:
            - ".env"
        networks:
            - intranet
        ports:
            - "3306:3306"
        volumes:
            - ./restore:/docker-entrypoint-initdb.d:ro
            - db_data:/var/lib/mysql

    phpmyadmin:
        container_name: phpmyadmin
        depends_on:
            - mariadb
        environment:
            - PMA_HOST=mariadb
        image: phpmyadmin/phpmyadmin:latest
        networks:
            - intranet
        ports:
            - "8080:80"

networks:
    intranet:
        driver: bridge

volumes:
    db_data:
