version: '3.3'

services:
    mariadb:
        container_name: mariadb
        image: mariadb:latest
        env_file:
            - ".env"
        networks:
            - intranet
        ports:
            - "3306:3306"
        restart: always
        volumes:
            - ./restore:/docker-entrypoint-initdb.d:ro
            - db_data:/var/lib/mysql
    phpmyadmin:
        container_name: phpmyadmin
        depends_on:
            - mariadb
        environment:
            - PMA_HOST=mariadb
        image: phpmyadmin/phpmyadmin:latest
        networks:
            - intranet
        ports:
            - "8080:80"
        restart: always

networks:
    intranet:
        driver: bridge

volumes:
    db_data:
